name: Cherry Blazer CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get -y install cmake clang-tidy-12

      - name: Configure
        run: >-
          cmake -S . -B ${{github.workspace}}/build
          -D CHERRY_BLAZER_CI=1
          -D CHERRY_BLAZER_DEBUG=1
          -D CHERRY_BLAZER_TEST=1
          -D CHERRY_BLAZER_OPTIMIZE=1
          -D CHERRY_BLAZER_ASAN=1
          -D CMAKE_CXX_CLANG_TIDY='clang-tidy-12;-warnings-as-errors=*'

      - name: Build
        run: cmake --build ${{github.workspace}}/build -- VERBOSE=1

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -V
