name: cherry-blazer-linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  parallel-nonverbose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Dependencies: install upstream cmake"
        run: |
          sudo bash <(curl -s https://apt.kitware.com/kitware-archive.sh)
          sudo apt-get -y install cmake
          echo -e "CMAKE VERSION: "
          cmake --version
      - name: "Dependencies: install system packages"
        run: |
          sudo apt-get -y install ninja-build clang-12 clang-tidy-12 llvm-12-dev libclang-12-dev
      - name: "Dependencies: build include-what-you-use"
        run: |
          git clone https://github.com/include-what-you-use/include-what-you-use.git
          cd include-what-you-use
          git checkout clang_12
          cmake -S . -B iwyu-build -GNinja -DCMAKE_PREFIX_PATH=/usr/lib/llvm-12
          cmake --build iwyu-build --
          cd ${{github.workspace}}
      - name: "Cherry Blazer: configure"
        run: >-
          cmake -S . -B cb-build -GNinja
          -D CHERRY_BLAZER_CI=1
          -D CHERRY_BLAZER_DEBUG=1
          -D CHERRY_BLAZER_TEST=1
          -D CHERRY_BLAZER_OPTIMIZE=1
          -D CHERRY_BLAZER_ASAN=1
          -D CMAKE_CXX_CLANG_TIDY='clang-tidy-12;-warnings-as-errors=*'
          -D CMAKE_CXX_INCLUDE_WHAT_YOU_USE='${{github.workspace}}/include-what-you-use/iwyu-build/bin/include-what-you-use;-Xiwyu;--mapping_file='$(pwd)'/iwyu.imp'
      - name: "Cherry Blazer: build"
        run: |
          cmake --build cb-build --
      - name: "Cherry Blazer: test"
        working-directory: cb-build
        run: |
          ctest --progress --output-on-failure -j$(nproc)
